apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-python-cronjob
  namespace: argocd
spec:
  schedule: "0 */4 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-script
              image: rupasna02/hello-python-cronjob:latest
          restartPolicy: OnFailure
